export default [
  {
    id: 1,
    postedOn: "2023-10-23",
    title: "Ios Developer",
    company: "Apple",
    type: "Mid Level",
    experience: "Fresher",
    location: "Remote",
    skills: ["swiftUI", "Unix", "CoreData"],
    jobLink: "https://www.apple.com/careers/in/",
  },
  {
    id: 2,
    postedOn: "2023-9-2",
    title: "Ios Developer",
    company: "Apple",
    type: "Mid Level",
    experience: "Fresher",
    location: "Remote",
    skills: ["swiftUI", "Unix", "CoreData"],
    jobLink: "https://www.apple.com/careers/in/",
  },
  {
    id: 3,
    postedOn: "2023-10-23",
    title: "Ios Developer",
    company: "Apple",
    type: "Mid Level",
    experience: "Fresher",
    location: "Remote",
    skills: ["swiftUI", "Unix", "CoreData"],
    jobLink: "https://www.apple.com/careers/in/",
  },
  {
    id: 4,
    postedOn: "2023-10-23",
    title: "Ios Developer",
    company: "Apple",
    type: "Mid Level",
    experience: "Fresher",
    location: "Remote",
    skills: ["swiftUI", "Unix", "CoreData"],
    jobLink: "https://www.apple.com/careers/in/",
  },
  {
    id: 5,
    postedOn: "2023-10-23",
    title: "Ios Developer",
    company: "Apple",
    type: "Mid Level",
    experience: "Fresher",
    location: "Remote",
    skills: ["swiftUI", "Unix", "CoreData"],
    jobLink: "https://www.apple.com/careers/in/",
  },
  {
    id: 6,
    postedOn: "2023-10-23",
    title: "Ios Developer",
    company: "Apple",
    type: "Mid Level",
    experience: "Fresher",
    location: "Remote",
    skills: ["swiftUI", "Unix", "CoreData"],
    jobLink: "https://www.apple.com/careers/in/",
  },
  {
    id: 7,
    postedOn: "2023-10-23",
    title: "Ios Developer",
    company: "Apple",
    type: "Mid Level",
    experience: "Fresher",
    location: "Remote",
    skills: ["swiftUI", "Unix", "CoreData"],
    jobLink: "https://www.apple.com/careers/in/",
  },
  {
    id: 8,
    postedOn: "2023-10-23",
    title: "Ios Developer",
    company: "Apple",
    type: "Mid Level",
    experience: "Fresher",
    location: "Remote",
    skills: ["swiftUI", "Unix", "CoreData"],
    jobLink: "https://www.apple.com/careers/in/",
  },
  {
    id: 9,
    postedOn: "2023-10-23",
    title: "Ios Developer",
    company: "Apple",
    type: "Mid Level",
    experience: "Fresher",
    location: "Remote",
    skills: ["swiftUI", "Unix", "CoreData"],
    jobLink: "https://www.apple.com/careers/in/",
  },
  {
    id: 10,
    postedOn: "2023-10-23",
    title: "Ios Developer",
    company: "Apple",
    type: "Mid Level",
    experience: "Fresher",
    location: "Remote",
    skills: ["swiftUI", "Unix", "CoreData"],
    jobLink: "https://www.apple.com/careers/in/",
  },
  {
    id: 11,
    postedOn: "2023-10-23",
    title: "Ios Developer",
    company: "Apple",
    type: "Mid Level",
    experience: "Fresher",
    location: "Remote",
    skills: ["swiftUI", "Unix", "CoreData"],
    jobLink: "https://www.apple.com/careers/in/",
  },
  {
    id: 12,
    postedOn: "2023-10-23",
    title: "Ios Developer",
    company: "Apple",
    type: "Mid Level",
    experience: "Fresher",
    location: "Remote",
    skills: ["swiftUI", "Unix", "CoreData"],
    jobLink: "https://www.apple.com/careers/in/",
  },
  {
    id: 13,
    postedOn: "2023-10-23",
    title: "Ios Developer",
    company: "Apple",
    type: "Mid Level",
    experience: "Fresher",
    location: "Remote",
    skills: ["swiftUI", "Unix", "CoreData"],
    jobLink: "https://www.apple.com/careers/in/",
  },
  {
    id: 14,
    postedOn: "2023-10-23",
    title: "Ios Developer",
    company: "Apple",
    type: "Mid Level",
    experience: "Fresher",
    location: "Remote",
    skills: ["swiftUI", "Unix", "CoreData"],
    jobLink: "https://www.apple.com/careers/in/",
  },
  {
    id: 15,
    postedOn: "2023-10-23",
    title: "Ios Developer",
    company: "Apple",
    type: "Mid Level",
    experience: "Fresher",
    location: "Remote",
    skills: ["swiftUI", "Unix", "CoreData"],
    jobLink: "https://www.apple.com/careers/in/",
  },
  {
    id: 16,
    postedOn: "2023-10-23",
    title: "Ios Developer",
    company: "Apple",
    type: "Mid Level",
    experience: "Fresher",
    location: "Remote",
    skills: ["swiftUI", "Unix", "CoreData"],
    jobLink: "https://www.apple.com/careers/in/",
  },
  {
    id: 17,
    postedOn: "2023-10-23",
    title: "Ios Developer",
    company: "Apple",
    type: "Mid Level",
    experience: "Fresher",
    location: "Remote",
    skills: ["swiftUI", "Unix", "CoreData"],
    jobLink: "https://www.apple.com/careers/in/",
  },
  {
    id: 18,
    postedOn: "2023-05-1",
    title: "Ios Developer",
    company: "Apple",
    type: "Mid Level",
    experience: "Fresher",
    location: "Remote",
    skills: ["swiftUI", "Unix", "CoreData"],
    jobLink: "https://www.apple.com/careers/in/",
  },
  {
    id: 19,
    postedOn: "2023-10-23",
    title: "Ios Developer",
    company: "Apple",
    type: "Mid Level",
    experience: "Fresher",
    location: "Remote",
    skills: ["swiftUI", "Unix", "CoreData"],
    jobLink: "https://www.apple.com/careers/in/",
  },
  {
    id: 20,
    postedOn: "2023-10-23",
    title: "Ios Developer",
    company: "Apple",
    type: "Mid Level",
    experience: "Fresher",
    location: "Remote",
    skills: ["swiftUI", "Unix", "CoreData"],
    jobLink: "https://www.apple.com/careers/in/",
  },
];
